steps:
  # Build the JAR
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'install']

  - name: gcr.io/cloud-builders/docker
    args:
      - '-c'
      - |
        docker --version
        dockerd > /dev/null 2>&1 &
        sleep 10
    entrypoint: bash

  - name: gcr.io/cloud-builders/mvn
    args:
      - clean
      - verify

  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/acquired-rarity-431700-f0/gcp-helloworld/gcp-helloworld:${SHORT_SHA}', '.']

  # Push to GCR
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/acquired-rarity-431700-f0/gcp-helloworld/gcp-helloworld:${SHORT_SHA}']

logsBucket: 'gs://srikar-gcp-builds'  # Replace with your Cloud Storage bucket name
options:
  logging: GCS_ONLY
