steps:
  # Step 1: Build the Maven project, including running tests
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'install']

  # Step 2: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/gcp-helloworld', '.']

  # Step 3: Push the Docker image to GCR
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/gcp-helloworld']

images:
  - 'gcr.io/$PROJECT_ID/gcp-helloworld'
